services:
  helmholtz:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      - PORT=3000
      - DISCORD_TOKEN=xxxx
      - DISCORD_GUILD_ID=xxxx
      - DISCORD_SOURCE_CHANNEL_ID=xxxx
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/key.json
      - ENABLE_CLOUD_LOGGING=false
      - ENABLE_SYNC_WITH_FIRESTORE=false
    volumes:
      - ./helmholtz-sa.json:/opt/key.json:ro